artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation

# YF settings
yfinance_config:
  # tickers: https://raw.githubusercontent.com/krishna-das-m/balance_continuous/refs/heads/main/data/SandP500Ticker.csv
  tickers: [
    AAPL, MSFT, NVDA, GOOGL, AMZN, META, BRK-B, AVGO, LLY, TSLA,
    WMT, JPM, V, UNH, XOM, MA, ORCL, COST, HD, PG,
    NFLX, JNJ, BAC, ABBV, CRM, KO, CVX, MRK, AMD, ADBE,
    PEP, TMO, WFC, CSCO, MCD, ACN, LIN, ABT, DHR, TXN,
    PM, VZ, QCOM, IBM, INTU, NOW, DIS, NEE, CAT, GE
  ]
  information_technology: [
    "AAPL",
    "ACN",
    "ADBE",
    "ADI",
    "ADSK",
    "AKAM",
    "AMAT",
    "AMD",
    "ANET",
    "APH",
    "APP",
    "AVGO",
    "CDNS",
    "CDW",
    "CRM",
    "CRWD",
    "CSCO",
    "CTSH",
    "DDOG",
    "DELL",
    "EPAM",
    "FFIV",
    "FICO",
    "FSLR",
    "FTNT",
    "GDDY",
    "GEN",
    "GLW",
    "HPE",
    "HPQ",
    "IBM",
    "INTC",
    "INTU",
    "IT",
    "JBL",
    "KEYS",
    "KLAC",
    "LRCX",
    "MCHP",
    "MPWR",
    "MSFT",
    "MSI",
    "MU",
    "NOW",
    "NTAP",
    "NVDA",
    "NXPI",
    "ON",
    "ORCL",
    "PANW",
    "PLTR",
    "PTC",
    "Q",
    "QCOM",
    "ROP",
    "SMCI",
    "SNPS",
    "STX",
    "SWKS",
    "TDY",
    "TEL",
    "TER",
    "TRMB",
    "TXN",
    "TYL",
    "VRSN",
    "WDAY",
    "WDC",
    "ZBRA"
  ]
  financials: [
    "ACGL",
    "AFL",
    "AIG",
    "AIZ",
    "AJG",
    "ALL",
    "AMP",
    "AON",
    "APO",
    "AXP",
    "BAC",
    "BEN",
    "BK",
    "BLK",
    "BRK.B",
    "BRO",
    "BX",
    "C",
    "CB",
    "CBOE",
    "CFG",
    "CINF",
    "CME",
    "COF",
    "COIN",
    "CPAY",
    "EG",
    "ERIE",
    "FDS",
    "FI",
    "FIS",
    "FITB",
    "GL",
    "GPN",
    "GS",
    "HBAN",
    "HIG",
    "HOOD",
    "IBKR",
    "ICE",
    "IVZ",
    "JKHY",
    "JPM",
    "KEY",
    "KKR",
    "L",
    "MA",
    "MCO",
    "MET",
    "MMC",
    "MS",
    "MSCI",
    "MTB",
    "NDAQ",
    "NTRS",
    "PFG",
    "PGR",
    "PNC",
    "PRU",
    "PYPL",
    "RF",
    "RJF",
    "SCHW",
    "SPGI",
    "STT",
    "SYF",
    "TFC",
    "TROW",
    "TRV",
    "USB",
    "V",
    "WFC",
    "WRB",
    "WTW",
    "XYZ"
  ]
  start_date: "2000-01-01"
  end_date: null  # null means current date
  interval: "1d"
  auto_adjust: False
# [AAPL, MSFT, GOOGL, AMZN, TSLA, META, NVDA, JPM, V, BRK-B]